<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModulSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('menu_modul')->insert([
            [
                'key' => "1_",
                'parent' => null,
                'kode_modul' => 1,
                'kode_key' => 0,
                'nama_modul' => 'PENJUALAN',
                'kode_grup' => 1,
                'nama_grup' => 'PENJUALAN',
                'nama_url' => '#',
                'level1' => 0,
                'level2' => 1,
                'level3' => 1,
                'level4' => 0,
                'level5' => 0,
                'level6' => 0,
                'level7' => 0,
                'level8' => 1,
                'level9' => 1,
                'textlevel' => '2389'
            ],
            [
                'key' => '2_',
                'parent' => null,
                'kode_modul' => 2,
                'kode_key' => 0,
                'nama_modul' => 'PEMBELIAN',
                'kode_grup' => 2,
                'nama_grup' => 'PEMBELIAN',
                'nama_url' => '#',
                'level1' => 0,
                'level2' => 1,
                'level3' => 1,
                'level4' => 0,
                'level5' => 0,
                'level6' => 0,
                'level7' => 0,
                'level8' => 1,
                'level9' => 1,
                'textlevel' => '2389'
            ],
            [
                'key' => '3_',
                'parent' => null,
                'kode_modul' => 3,
                'kode_key' => 0,
                'nama_modul' => 'UTANG',
                'kode_grup' => 3,
                'nama_grup' => 'UTANG',
                'nama_url' => '#',
                'level1' => 0,
                'level2' => 0,
                'level3' => 0,
                'level4' => 0,
                'level5' => 0,
                'level6' => 0,
                'level7' => 0,
                'level8' => 0,
                'level9' => 1,
                'textlevel' => '9'
            ],
            [
                'key' => '4_',
                'parent' => null,
                'kode_modul' => 4,
                'kode_key' => 0,
                'nama_modul' => 'PIUTANG',
                'kode_grup' => 4,
                'nama_grup' => 'PIUTANG',
                'nama_url' => '#',
                'level1' => 0,
                'level2' => 0,
                'level3' => 1,
                'level4' => 0,
                'level5' => 0,
                'level6' => 0,
                'level7' => 0,
                'level8' => 0,
                'level9' => 1,
                'textlevel' => '39'
            ],
            [
                'key' => '5_',
                'parent' => null,
                'kode_modul' => 5,
                'kode_key' => 0,
                'nama_modul' => 'PERSEDIAAN',
                'kode_grup' => 5,
                'nama_grup' => 'PERSEDIAAN',
                'nama_url' => '#',
                'level1' => 0,
                'level2' => 0,
                'level3' => 0,
                'level4' => 0,
                'level5' => 0,
                'level6' => 0,
                'level7' => 0,
                'level8' => 0,
                'level9' => 1,
                'textlevel' => '39'
            ],
            [
                'key' => '6_',
                'parent' => null,
                'kode_modul' => 6,
                'kode_key' => 0,
                'nama_modul' => 'LAPORAN',
                'kode_grup' => 6,
                'nama_grup' => 'LAPORAN',
                'nama_url' => '#',
                'level1' => 0,
                'level2' => 0,
                'level3' => 1,
                'level4' => 0,
                'level5' => 0,
                'level6' => 0,
                'level7' => 0,
                'level8' => 0,
                'level9' => 1,
                'textlevel' => '39'
            ],
            [
                'key' => '7_',
                'parent' => null,
                'kode_modul' => 7,
                'kode_key' => 0,
                'nama_modul' => 'AKUNTANSI',
                'kode_grup' => 7,
                'nama_grup' => 'AKUNTANSI',
                'nama_url' => '#',
                'level1' => 0,
                'level2' => 0,
                'level3' => 0,
                'level4' => 0,
                'level5' => 0,
                'level6' => 0,
                'level7' => 0,
                'level8' => 1,
                'level9' => 1,
                'textlevel' => '39',
            ],
            [
                'key' => '8_',
                'parent' => null,
                'kode_modul' => 8,
                'kode_key' => 0,
                'nama_modul' => 'DAFTAR',
                'kode_grup' => 8,
                'nama_grup' => 'DAFTAR',
                'nama_url' => '#',
                'level1' => 0,
                'level2' => 0,
                'level3' => 0,
                'level4' => 0,
                'level5' => 0,
                'level6' => 0,
                'level7' => 0,
                'level8' => 1,
                'level9' => 1,
                'textlevel' => '89'
            ],
            [
                'key' => '9_',
                'parent' => null,
                'kode_modul' => 9,
                'kode_key' => 0,
                'nama_modul' => 'KONFIGURASI',
                'kode_grup' => 9,
                'nama_grup' => 'KONFIGURASI',
                'nama_url' => '#',
                'level1' => 0,
                'level2' => 0,
                'level3' => 0,
                'level4' => 0,
                'level5' => 0,
                'level6' => 0,
                'level7' => 0,
                'level8' => 1,
                'level9' => 1,
                'textlevel' => '89'
            ],
            [
                'key' => '9_1',
                'parent' => '9_',
                'kode_modul' => 9.01,
                'kode_key' => 9,
                'nama_modul' => 'Manajemen Modul',
                'kode_grup' => 9,
                'nama_grup' => 'Manajemen Modul',
                'nama_url' => 'konfigurasi/manajemen-moduls',
                'level1' => 0,
                'level2' => 0,
                'level3' => 0,
                'level4' => 0,
                'level5' => 0,
                'level6' => 0,
                'level7' => 0,
                'level8' => 1,
                'level9' => 1,
                'textlevel' => '89'
            ],
            [
                'key' => '9_2',
                'parent' => '9_',
                'kode_modul' => 9.02,
                'kode_key' => 9,
                'nama_modul' => 'Manajemen Menu',
                'kode_grup' => 9,
                'nama_grup' => 'Manajemen Menu',
                'nama_url' => 'konfigurasi/manajemen-menus',
                'level1' => 0,
                'level2' => 0,
                'level3' => 0,
                'level4' => 0,
                'level5' => 0,
                'level6' => 0,
                'level7' => 0,
                'level8' => 1,
                'level9' => 1,
                'textlevel' => '89'
            ]
        ]);
    }
}
